# Generated by Django 4.2.4 on 2023-08-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
